# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Carson's Data Science Blog"
email: carsonpayne4@gmail.com
description: "This is my blog to share my thoughts and projects about data science." 
baseurl: 
url: "https://carsonp4.github.io" #  change this to "https://<your-github-username>.github.io"
image: https://media.licdn.com/dms/image/C5603AQFzEcRa0Emnxg/profile-displayphoto-shrink_400_400/0/1651436149790?e=1700697600&v=beta&t=HsFJG35_POFRJAwnYojjVUKJAJ8YZMZdk2Xwd_hgB4Y
author: Carson Payne
copyright: CAP # Your initials or what you want the copyright to be.  Leave empty for no copyright
footer_description: "Hope you enjoy your stay!"


# Social media users names.  Leave fields blank that you don't want displayed
github_username:  carsonp4
linkedin_username: carsonpayne
facebook_username: Carson Payne
instagram_username: carson_payne1

plugins:
  - jekyll-feed

